var child_process = require("child_process")
var fs = require("fs")
var path = require("path")

console.log("Build Step 1 of 5")
child_process.execSync("mkdir node_modules")
console.log("Build Step 2 of 5")
child_process.execSync("cp -r ../../pluginreference ./node_modules/terrariaserver-lite")
console.log("Build Step 3 of 5")
child_process.execSync("npm run build:core")
console.log("Build Step 4 of 5")
child_process.execSync("npm run build:packed")
console.log("Build Step 5 of 5")
fs.renameSync("./output", "./plugin")
